### ISSUE TITLE
Add new behavior to button RUN

### ISSUE THREAD

**Issue by wololoa** [micronjs/micronjs#13]
In the editor, change the button run to "stop" when the game is running. This should completely reset/stop the iframe of the game/editor. It can be distracting to have it all the time in execution. 
Add a function if you want to stop it programatically.

**Comment by wololoa** [comment]
@ertrzyiks remember to clear the iframe when the game is stopped/restarted.

**Comment by ertrzyiks** [comment]
![http://media3.giphy.com/media/k7asdMmmSadNu/giphy.gif](http://media3.giphy.com/media/k7asdMmmSadNu/giphy.gif)

**Comment by ertrzyiks** [comment]
i mean, its polish no, which means yes
